exports.SUCCESS = 'Transaction Successful'
exports.FAILURE = 'Transaction Failed'
exports.INVALID_INPUT = 'Invalid Input'
exports.INVALID_SIGNATURE = 'Improperly Formated Signature'
exports.INVALID_SIGNER = 'Wrong Signing Address or Wrong Nonce'
